# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ifraixedes"
license = "MIT"
licenselink = "https://github.com/ifraixedes/hugo-theme/blob/master/LICENSE.md"
description = "My Hugo Theme"
homepage = "http://blog.fraixed.es/"
tags = ["blog", "personal", "techy"]
min_version = 0.13

[author]
  name = "Ivan Fraixedes"
  homepage = "http://ivan.fraixed.es"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
